### ISSUE TITLE
gkroam-insert cannot create new files

### ISSUE THREAD

**Issue by guidao** [Kinneyzhang/gkroam#21]
gkroam-insert "consul"

![image](https://user-images.githubusercontent.com/3192136/95939496-d1601c80-0e0e-11eb-9a70-7d8c75c6cdcf.png)

**Comment by guidao** [comment]
还有个问题，headline不显示中文
---
![image](https://user-images.githubusercontent.com/3192136/95939692-3f0c4880-0e0f-11eb-97de-ff8d449d8f3d.png)

**Comment by guidao** [comment]
在 gkroam-toggle-prettify 关闭的状态下，没有显示行号，然后我移动的时候，就会抖动。
---
![Kapture 2020-10-14 at 11 28 03](https://user-images.githubusercontent.com/3192136/95940277-86470900-0e10-11eb-94eb-22a96ead73a5.gif)

**Comment by Kinneyzhang** [comment]
前两个问题修复了。最后一个行号的问题，我没能复现，但是做了一些修改，你更新完后试试还有没有问题。

**Comment by guidao** [comment]
display-line-numbers-mode 换成这个可以了。

**Comment by Kinneyzhang** [comment]
嗯嗯，```line-number-mode``` 有bug而且性能不好。现在都用 ```display-line-numbers-mode```。

**Comment by guidao** [comment]
多谢大佬，试了下，都没问题了。
